name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authentification GCP avec le bon project_id
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          docker build --platform=linux/amd64 -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated