name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Authentification avec GCP via le service account
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Étape 3 : Installer les outils gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      # Étape 4 : Configurer Docker pour pousser vers Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      # Étape 5 : Build & Push de l’image Docker vers Artifact Registry
      - name: Build and Push Docker image
        run: |
          docker build --platform=linux/amd64 -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app

      # Étape 6 : Déploiement sur Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated