name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build --platform=linux/amd64 -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-flask-app \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
